format = "$all$character"

right_format = "$directory"

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 20

# Disable the blank line at the start of the prompt
add_newline = true
